# Generated by Django 4.2.6 on 2024-04-30 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'care',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id_pictures', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('address', models.CharField(max_length=60)),
                ('zip', models.IntegerField()),
                ('city', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('last_connexion', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
                ('visibility', models.BooleanField()),
                ('read', models.BooleanField()),
                ('id_care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.care')),
                ('id_pictures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.pictures')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.AddField(
            model_name='care',
            name='keeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kept_cares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='care',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id_advice', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('like', models.IntegerField(null=True)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.category')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advice',
            },
        ),
    ]
