# Generated by Django 4.2.6 on 2024-06-26 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_rename_id_user_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id_pictures',
        ),
        migrations.AddField(
            model_name='advice',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='care',
            name='botaniste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='botaniste', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(default='none', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.post'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'botanist')], default='owner', max_length=10),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.post')),
            ],
        ),
    ]
