# Generated by Django 4.2.6 on 2024-07-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0004_rename_comment_comment_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'botanist')], default='owner', max_length=10),
        ),
    ]
