# Generated by Django 4.2.6 on 2024-07-05 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='keeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kept_cares', to=settings.AUTH_USER_MODEL),
        ),
    ]
